# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002bd156a2becb37633b54de5733a57c93798bb99419b2040f9255893965bea5e7df7be553dc2c2c0c76b42cb837c2dcf75cf15827696d235164f1822aecc073

test:
  secret_key_base: 7677f1c80a54c862c223efb021ff692ebe2b3657ede4b777dfe5c11c702ce0f1b089d13afd13a1d45d6261f324cd98a3d1541598d4110edac13f3f9bf6c10068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
